# Etapa 1: Build da aplicação
FROM node:18 AS build

WORKDIR /app

COPY package*.json ./
COPY angular.json ./
COPY tsconfig.json ./

RUN npm install

COPY projects/mf-login ./projects/mf-login
RUN npm run build:mf-login

# Etapa 2: Servir com Nginx
FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/*
COPY --from=build /app/dist/mf-login/browser /usr/share/nginx/html
COPY projects/mf-login/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
