version: "3.8"
services:
  host:
    build:
      context: ./projects/host
      dockerfile: Dockerfile
    ports:
      - "8080:80"
  mf-login:
    build:
      context: ./projects/mf-login
      dockerfile: Dockerfile
    ports:
      - "8081:80"
  mf-customers:
    build:
      context: ./projects/mf-customers
      dockerfile: Dockerfile
    ports:
      - "8082:80"
