version: "3.8"
services:
  host:
    build:
      context: .
      dockerfile: projects/host/Dockerfile
    ports:
      - "8080:80"

  mf-login:
    build:
      context: .
      dockerfile: projects/mf-login/Dockerfile
    ports:
      - "8081:80"

  mf-customers:
    build:
      context: .
      dockerfile: projects/mf-customers/Dockerfile
    ports:
      - "8082:80"
